### ISSUE TITLE
 Cannot find module

### ISSUE THREAD

**Issue by mehdiraized** [beyonk-adventures/svelte-mapbox#10] opened 2020-05-31 11:55 UTC
Error: Cannot find module '/front/node_modules/@beyonk/svelte-mapbox/index.mjs'. Please verify that the package.json has a valid "main" entry

```
at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/front/__sapper__/dev/server/server.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/front/node_modules/@beyonk/svelte-mapbox/package.json',
  requestPath: '@beyonk/svelte-mapbox'
```

**Comment by antony** [comment] 2020-05-31 12:15
@mehdiraized without knowing anything about how you are trying to bundle this into your application, I can't help you.

Please let me know if you are using Rollup or Webpack or Parcel, what stack you are using, etc

**Comment by mehdiraized** [comment] 2020-05-31 12:32
Rollup

> @mehdiraized without knowing anything about how you are trying to bundle this into your application, I can't help you.
> 
> Please let me know if you are using Rollup or Webpack or Parcel, what stack you are using, etc

**Comment by antony** [comment] 2020-05-31 12:34
@mehdiraized please post your rollup config, details about how you installed the module, details about how you're importing the module into your project etc

**Comment by mehdiraized** [comment] 2020-05-31 12:40
config default sapper
```
import svelte from "rollup-plugin-svelte";
import alias from "@rollup/plugin-alias";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import replace from "@rollup/plugin-replace";
import sveltePreprocess from "svelte-preprocess";
import babel from "@rollup/plugin-babel";
import { terser } from "rollup-plugin-terser";
import config from "sapper/config/rollup.js";
import pkg from "./package.json";

const mode = process.env.NODE_ENV;
const dev = mode === "development";
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) =>
  (warning.code === "CIRCULAR_DEPENDENCY" &&
    /[/\\]@sapper[/\\]/.test(warning.message)) ||
  onwarn(warning);
const dedupe = ["svelte", "svelte/internal"];

const preprocess = sveltePreprocess({
  scss: {
    includePaths: ["src"],
  },
  postcss: {
    plugins: [require("autoprefixer")],
  },
});

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    cache: true,
    plugins: [
      replace({
        "process.browser": true,
        "process.env.NODE_ENV": JSON.stringify(mode),
      }),
      svelte({
        dev,
        hydratable: true,
        emitCss: true,
        preprocess,
      }),
      alias({
        entries: [
          {
            find: `@sapper`,
            replacement: `${__dirname}/src/node_modules/@sapper`,
          },
        ],
      }),
      resolve({
        browser: true,
        dedupe,
      }),
      commonjs(!dev && { sourceMap: false }),

      legacy &&
        babel({
          extensions: [".js", ".mjs", ".html", ".svelte"],
          babelHelpers: "runtime",
          exclude: ["node_modules/@babel/**"],
          presets: [
            [
              "@babel/preset-env",
              {
                targets: "> 0.25%, not dead",
              },
            ],
          ],
          plugins: [
            "@babel/plugin-syntax-dynamic-import",
            [
              "@babel/plugin-transform-runtime",
              {
                useESModules: true,
              },
            ],
          ],
        }),

      !dev &&
        terser({
          module: true,
        }),
    ],

    preserveEntrySignatures: false,
    onwarn,
  },

  server: {
    input: config.server.input(),
    output: config.server.output(),
    cache: true,
    plugins: [
      replace({
        "process.browser": false,
        "process.env.NODE_ENV": JSON.stringify(mode),
      }),
      svelte({
        generate: "ssr",
        hydratable: true,
        dev,
        preprocess,
      }),
      alias({
        entries: [
          {
            find: `@sapper`,
            replacement: `${__dirname}/src/node_modules/@sapper`,
          },
        ],
      }),
      resolve({
        dedupe,
      }),
      commonjs(!dev && { sourceMap: false }),
    ],
    external: Object.keys(pkg.dependencies).concat(
      require("module").builtinModules ||
        Object.keys(process.binding("natives"))
    ),

    onwarn,
  },

  serviceworker: {
    input: config.serviceworker.input(),
    output: config.serviceworker.output(),
    cache: true,
    plugins: [
      resolve(),
      replace({
        "process.browser": true,
        "process.env.NODE_ENV": JSON.stringify(mode),
      }),
      alias({
        entries: [
          {
            find: `@sapper`,
            replacement: `${__dirname}/src/node_modules/@sapper`,
          },
        ],
      }),
      commonjs(!dev && { sourceMap: false }),
      !dev && terser(),
    ],

    onwarn,
  },
};
```

**Comment by antony** [comment] 2020-05-31 12:41
You need to ensure you're installing as a development dependency:

`npm install --save-dev @beyonk/svelte-mapbox`

**Comment by antony** [comment] 2020-05-31 12:42
Duplicate of #1 and #3

**Closed by antony** 2020-05-31 12:42 UTC
Labels: duplicate

**Comment by mehdiraized** [comment] 2020-05-31 12:45
plz add to readme file

> Duplicate of #1 and #3

**Comment by antony** [comment] 2020-05-31 12:47
Done - https://github.com/beyonk-adventures/svelte-mapbox/commit/b9f623c82e747006045bf029113efc6bf1457eb0

It's important that you understand that this applies to any library you use with Svelte/Sapper. You do not need runtime dependencies except in very specific circumstances.
